export const FETCH_POSTS='FETCH_POSTS'
export const NEW_POST = "NEW_POST";
export const LOGIN = "LOGIN";
export const GETSERVESIES = "GETSERVESIES";
export const REVERSE_GEOLOCATION="REVERSE_GEOLOCATION";
export const SETCOORDINATES="SETCOORDINATES";

export const COMPONENT_ENTER="COMPONENT_ENTER";
export const GETSELECTED_SERVICES="GETSELECTED_SERVICES";
export const ORDER_OBJ="ORDER_OBJ"
