export const FETCH_POSTS='FETCH_POSTS'
export const NEW_POST = "NEW_POST";
export const LOGIN = "LOGIN";
export const ACTIVATION_STATE="ACTIVATION_STATE"

export const GETSERVESIES = "GETSERVESIES";
export const REVERSE_GEOLOCATION="REVERSE_GEOLOCATION";
export const SETCOORDINATES="SETCOORDINATES";
export const SET_DRIVER_COORDINATES="SET_DRIVER_COORDINATES";

export const REFRESH_PLAYER_ID="REFRESH_PLAYER_ID"
export const COMPONENT_ENTER="COMPONENT_ENTER";
export const GETSELECTED_SERVICES="GETSELECTED_SERVICES";
export const ORDER_OBJ="ORDER_OBJ"

export const PROVIDER_INFO="PROVIDER_INFO"
export const RATE_PROVIDER="RATE_PROVIDER"

export const ORDER_ID="ORDER_ID"
export const CANCEL_ORDER="CANCEL_ORDER"
export const GET_FAV_LOCS="GET_FAV_LOCS"
export const ADD_FAV_LOC="ADD_FAV_LOC"

