// leave off @2x/@3x
const images = {
  logo: require('../assets/ir.png'),
  clearLogo: require('../assets/top_logo.png'),
  launch: require('../assets/launch-icon.png'),
  ready: require('../assets/your-app.png'),
  ignite: require('../assets/ignite_logo.png'),
  igniteClear: require('../assets/ignite-logo-transparent.png'),
  tileBg: require('../assets/tile_bg.png'),
  background: require('../assets/BG.png'),
  // drivrMarker: require('../assets/Group 1353.png'),

  buttonBackground: require('../assets/button-bg.png'),
  api: require('../assets/Icons/icon-api-testing.png'),
  components: require('../assets/Icons/icon-components.png'),
  deviceInfo: require('../assets/Icons/icon-device-information.png'),
  faq: require('../assets/Icons/faq-icon.png'),
  home: require('../assets/Icons/icon-home.png'),
  theme: require('../assets/Icons/icon-theme.png'),
  usageExamples: require('../assets/Icons/icon-usage-examples.png'),
  chevronRight: require('../assets/Icons/chevron-right.png'),
  hamburger: require('../assets/Icons/hamburger.png'),
  backButton: require('../assets/Icons/back-button.png'),
  closeButton: require('../assets/Icons/close-button.png'),
  loginBackground:require('../assets/Assets/loginBackground.png'),
  loginLogo:require('../assets/Assets/loginLogo.png'),
  SaudiFlag:require('../assets/Assets/SaudiFlag.png'),
  USFlag:require('../assets/Assets/USFlag.png'),
  IndiaFlag:require('../assets/Assets/IndiaFlag.png'),
  User:require("../assets/Assets/userHead.png"),
  logoCenter:require("../assets/Assets/logoCenter.png"),
  pinIcon:require("../assets/Icons/Pin-icon.png"),
  sataliteIcon:require("../assets/Icons/Satalite-icon.png"),
  kabbaIcon:require("../assets/Icons/Kabba-icon.png"),
  locatiOnMapIcon:require("../assets/Icons/LocatiOnMap-icon.png"),
  pluming:require("../assets/Assets/pluming.png"),
  pickup:require("../assets/Assets/pickup.png"),
  waterconnect:require("../assets/Assets/waterconnect.png"),
  stahat:require("../assets/Assets/stahat.png"),
  MainSarf:require("../assets/Assets/MainSarf.png")
}

export default images
